max_obstacle_height: 1.50

footprint_padding: 0.05
# rough measurements places the spot at 3.05m by 1.3m
robot_radius: 0.5
#footprint: [[1.525, 0.65], [-1.525, 0.65], [-1.525, -0.65], [1.525, -0.65]]  #  actual (centered)
  # [0     3]
  #  |     |
  #  |  X  |
  #  |     |
  # [1     2]

obstacle_layer:
  enabled:              true
  max_obstacle_height:  1
  origin_z:             0.0
  z_resolution:         0.2
  z_voxels:             10
  unknown_threshold:    15
  mark_threshold:       0
  combination_method:   1
  track_unknown_space:  true  # true needed for disabling global path planning through unknown space
  obstacle_range: 2.5
  raytrace_range: 3.0
  publish_voxel_map: false
  observation_sources: laser
  laser:
    data_type: LaserScan
    topic: /scan
    marking: true
    clearing: true
    inf_is_valid: true

#cost_scaling_factor and inflation_radius were now moved to the inflation_layer ns
inflation_layer:
  enabled:              true
  cost_scaling_factor:  10.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.25  # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true

